### ISSUE TITLE
Support for V1 of the Jira API

### ISSUE THREAD

**Issue by jessicard** [bugsnag/bugsnag-notification-plugins#190]
Right now we support V2, which was released in the beginning of 2012. V1 support would be :+1:

**Comment by indirect** [comment]
Looks like I don't need v1 support! It actually works perfectly for me when I make the request myself (I redacted some bits with `????`):

```
POST https://developer.????.org/jira/rest/api/2/issue
Accept: */*
Content-Type: application/json
Authorization: Basic ????==
Accept-Language: en-us
Accept-Encoding: gzip, deflate

{
    "fields": {
       "project":
       {
          "key": “????”
       },
       "summary": "ARGHHHHHH",
       "issuetype": {
          "name": "Task"
       }
   }
}

Content-Type: application/json;charset=UTF-8
X-Seraph-LoginReason: OK
Set-Cookie: JSESSIONID=????; Path=/jira; HttpOnly, atlassian.xsrf.token=????; Path=/jira
Server: nginx/1.0.0
X-AREQUESTID: 998x106518x1
X-ASEN: SEN-2000971
Transfer-Encoding: Identity
Content-Encoding: gzip
Cache-Control: no-cache, no-store, no-transform
Date: Mon, 10 Aug 2015 23:38:10 GMT
X-AUSERNAME: aarko
Connection: keep-alive
X-ASESSIONID: artmlu
X-Content-Type-Options: nosniff
Vary: User-Agent

{"id":"27945","key”:”????-113","self":"https://developer.????.org/jira/rest/api/2/issue/27945"}
```

**Comment by indirect** [comment]
Seems like the Jira plugin doesn't actually work:

```
$ coffee plugins/jira/index.coffee --host='https://developer.????.org/jira' --projectKey=???? --issueType="Task" --username=aarko --password='????'
Error firing notification
 { status: 404, message: undefined, body: {} }
```

Somewhat related, when I tried to use the `global-tunnel` npm package to redirect the HTTP request through a debugging proxy, I got this exception:

```
TypeError: Request path contains unescaped characters.
  at new ClientRequest (_http_client.js:73:11)
  at TunnelingAgent.exports.request (http.js:49:10)
  at TunnelingAgent.createSocket (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/global-tunnel/node_modules/tunnel/lib/tunnel.js:116:25)
  at TunnelingAgent.createSecureSocket [as createSocket] (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/global-tunnel/node_modules/tunnel/lib/tunnel.js:188:41)
  at TunnelingAgent.addRequest (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/global-tunnel/node_modules/tunnel/lib/tunnel.js:80:8)
  at new ClientRequest (_http_client.js:154:16)
  at Object.exports.request (http.js:49:10)
  at Object.globalTunnel._defaultedAgentRequest (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/global-tunnel/index.js:211:38)
  at Object.exports.request (https.js:136:15)
  at Object.globalTunnel._defaultedAgentRequest (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/global-tunnel/index.js:211:38)
  at Request.request (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/superagent/lib/node/index.js:541:28)
  at Request.set (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/superagent/lib/node/index.js:215:8)
  at Request.auth (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/superagent/lib/node/index.js:494:15)
  at Function.Jira.jiraRequest (/Users/andre/src/bugsnag/bugsnag-notification-plugins/plugins/jira/index.coffee:46:8)
  at Function.Jira.openIssue (/Users/andre/src/bugsnag/bugsnag-notification-plugins/plugins/jira/index.coffee:103:6)
  at Function.Jira.receiveEvent (/Users/andre/src/bugsnag/bugsnag-notification-plugins/plugins/jira/index.coffee:124:8)
  at Function.module.exports.NotificationPlugin.fireTestEvent (/Users/andre/src/bugsnag/bugsnag-notification-plugins/notification-plugin.coffee:158:6)
  at Object.<anonymous> (/Users/andre/src/bugsnag/bugsnag-notification-plugins/notification-plugin.coffee:239:10)
  at Object.<anonymous> (/Users/andre/src/bugsnag/bugsnag-notification-plugins/notification-plugin.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.loadFile (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/andre/src/bugsnag/bugsnag-notification-plugins/plugins/jira/index.coffee:1:22)
  at Object.<anonymous> (/Users/andre/src/bugsnag/bugsnag-notification-plugins/plugins/jira/index.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.exports.run (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/coffee-script/lib/coffee-script/coffee-script.js:119:23)
  at compileScript (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/coffee-script/lib/coffee-script/command.js:207:29)
  at compilePath (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/coffee-script/lib/coffee-script/command.js:160:14)
  at Object.exports.run (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/coffee-script/lib/coffee-script/command.js:95:21)
  at Object.<anonymous> (/Users/andre/src/bugsnag/bugsnag-notification-plugins/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

If that's true, maybe Jira is returning a 404 because the plugin isn't escaping the URL correctly?

**Comment by snmaynard** [comment]
We've rewritten our JIRA plugin so I'm hopeful this is fixed. If its not and you're having issues can you ping a support request to us and we can take a look!
